# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coordination.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'coordination.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63oordination.proto\x12\x16\x66\x65\x64med.coordination.v1\"\x90\x02\n\x11RoundStartRequest\x12\x10\n\x08round_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\x12\x1d\n\x15\x66lower_server_address\x18\x03 \x01(\t\x12L\n\nfit_config\x18\x04 \x03(\x0b\x32\x38.fedmed.coordination.v1.RoundStartRequest.FitConfigEntry\x12\x15\n\rdeadline_unix\x18\x05 \x01(\x03\x12\x1d\n\x15min_available_clients\x18\x06 \x01(\x05\x1a\x30\n\x0e\x46itConfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"k\n\rRoundStartAck\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x10\n\x08round_id\x18\x02 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x03 \x01(\x08\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\x15\n\rreceived_unix\x18\x05 \x01(\x03\"5\n\x11RoundAbortRequest\x12\x10\n\x08round_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\"6\n\x10HeartbeatRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\tsent_unix\x18\x02 \x01(\x03\"/\n\x0cHeartbeatAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x13\n\x0bserver_unix\x18\x02 \x01(\x03\x32\xb1\x02\n\x10NodeCoordination\x12\x64\n\x10NotifyRoundStart\x12).fedmed.coordination.v1.RoundStartRequest\x1a%.fedmed.coordination.v1.RoundStartAck\x12Z\n\x10NotifyRoundAbort\x12).fedmed.coordination.v1.RoundAbortRequest\x1a\x1b.fedmed.coordination.v1.Ack\x12[\n\tHeartbeat\x12(.fedmed.coordination.v1.HeartbeatRequest\x1a$.fedmed.coordination.v1.HeartbeatAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordination_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUNDSTARTREQUEST_FITCONFIGENTRY']._loaded_options = None
  _globals['_ROUNDSTARTREQUEST_FITCONFIGENTRY']._serialized_options = b'8\001'
  _globals['_ROUNDSTARTREQUEST']._serialized_start=47
  _globals['_ROUNDSTARTREQUEST']._serialized_end=319
  _globals['_ROUNDSTARTREQUEST_FITCONFIGENTRY']._serialized_start=271
  _globals['_ROUNDSTARTREQUEST_FITCONFIGENTRY']._serialized_end=319
  _globals['_ROUNDSTARTACK']._serialized_start=321
  _globals['_ROUNDSTARTACK']._serialized_end=428
  _globals['_ROUNDABORTREQUEST']._serialized_start=430
  _globals['_ROUNDABORTREQUEST']._serialized_end=483
  _globals['_ACK']._serialized_start=485
  _globals['_ACK']._serialized_end=502
  _globals['_HEARTBEATREQUEST']._serialized_start=504
  _globals['_HEARTBEATREQUEST']._serialized_end=558
  _globals['_HEARTBEATACK']._serialized_start=560
  _globals['_HEARTBEATACK']._serialized_end=607
  _globals['_NODECOORDINATION']._serialized_start=610
  _globals['_NODECOORDINATION']._serialized_end=915
# @@protoc_insertion_point(module_scope)
