FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir tenseal==0.3.14

COPY central_server/generate_keys.py central_server/generate_keys.py
COPY encryption/ encryption/

CMD ["python", "central_server/generate_keys.py"]
