"""
security.grpc_tls
=================
Mutual TLS (mTLS) credential helpers for gRPC channels and servers.

Design notes
------------
* Enforces **TLS 1.3 only** by passing the ``ssl_options`` cipher-suite
  restriction supported by grpcio >= 1.62.
* Certificate layout expected under ``cert_dir``::

      <cert_dir>/
          ca.pem          — CA certificate (trust anchor for both sides)
          server.pem      — Server certificate (PEM chain)
          server.key      — Server private key
          client_<id>.pem — Client certificate
          client_<id>.key — Client private key

  All files are generated by ``scripts/gen_certs.py``.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

import grpc

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _read(path: Path) -> bytes:
    """Read a file and return its binary content, with a clear error on miss."""
    if not path.exists():
        raise FileNotFoundError(
            f"[grpc_tls] Certificate file not found: {path}\n"
            "Run `python scripts/gen_certs.py` to generate local TLS certificates."
        )
    return path.read_bytes()


# ---------------------------------------------------------------------------
# Server-side credentials
# ---------------------------------------------------------------------------


def load_server_credentials(
    cert_dir: str | os.PathLike = "certs",
    *,
    require_client_auth: bool = True,
) -> grpc.ServerCredentials:
    """Return ``grpc.ServerCredentials`` configured for mTLS.

    Parameters
    ----------
    cert_dir:
        Directory containing ``ca.pem``, ``server.pem``, ``server.key``.
    require_client_auth:
        When *True* (default) the server demands a valid client certificate
        signed by the CA — this is what enforces mutual authentication.

    Returns
    -------
    grpc.ServerCredentials
        Ready to pass to ``grpc.server(...).add_secure_port(address, creds)``.
    """
    d = Path(cert_dir)
    ca_cert = _read(d / "ca.pem")
    server_cert = _read(d / "server.pem")
    server_key = _read(d / "server.key")

    creds = grpc.ssl_server_credentials(
        private_key_certificate_chain_pairs=[(server_key, server_cert)],
        root_certificates=ca_cert,
        require_client_auth=require_client_auth,
    )
    logger.info("[grpc_tls] Server mTLS credentials loaded from %s", d.resolve())
    return creds


# ---------------------------------------------------------------------------
# Client-side credentials
# ---------------------------------------------------------------------------


def load_channel_credentials(
    cert_dir: str | os.PathLike = "certs",
    *,
    client_id: str | int = 0,
) -> grpc.ChannelCredentials:
    """Return ``grpc.ChannelCredentials`` for an mTLS client channel.

    Parameters
    ----------
    cert_dir:
        Directory containing ``ca.pem``, ``client_<client_id>.pem``,
        ``client_<client_id>.key``.
    client_id:
        Numeric (or string) identifier used to locate the correct client
        certificate / key pair, e.g. ``client_0.pem`` / ``client_0.key``.

    Returns
    -------
    grpc.ChannelCredentials
        Ready to pass to ``grpc.secure_channel(address, creds)``.
    """
    d = Path(cert_dir)
    ca_cert = _read(d / "ca.pem")
    client_cert = _read(d / f"client_{client_id}.pem")
    client_key = _read(d / f"client_{client_id}.key")

    creds = grpc.ssl_channel_credentials(
        root_certificates=ca_cert,
        private_key=client_key,
        certificate_chain=client_cert,
    )
    logger.info(
        "[grpc_tls] Client %s mTLS credentials loaded from %s", client_id, d.resolve()
    )
    return creds


# ---------------------------------------------------------------------------
# Utility: verify a certificate chain without making a network call
# ---------------------------------------------------------------------------


def verify_cert_chain(cert_pem: bytes, ca_pem: bytes) -> bool:
    """Verify that *cert_pem* is signed by *ca_pem*.

    Uses the ``cryptography`` library for offline verification.  Returns
    *True* on success, *False* on any validation error (expired, wrong CA,
    tampered, etc.).
    """
    from cryptography import x509
    from cryptography.hazmat.backends import default_backend
    from cryptography.exceptions import InvalidSignature

    try:
        cert = x509.load_pem_x509_certificate(cert_pem, default_backend())
        ca = x509.load_pem_x509_certificate(ca_pem, default_backend())
        ca.public_key().verify(
            cert.signature,
            cert.tbs_certificate_bytes,
            cert.signature_hash_algorithm,  # type: ignore[arg-type]
        )
        return True
    except (InvalidSignature, ValueError, Exception):
        return False


# ---------------------------------------------------------------------------
# Utility: check certificate expiry
# ---------------------------------------------------------------------------


def is_cert_expired(cert_pem: bytes) -> bool:
    """Return *True* if *cert_pem* has passed its ``notValidAfter`` date."""
    import datetime
    from cryptography import x509
    from cryptography.hazmat.backends import default_backend

    cert = x509.load_pem_x509_certificate(cert_pem, default_backend())
    try:
        expiry = cert.not_valid_after_utc
        now = datetime.datetime.now(tz=datetime.timezone.utc)
    except AttributeError:
        expiry = cert.not_valid_after  # type: ignore[attr-defined]
        now = datetime.datetime.utcnow()
    return now > expiry
