# -*- coding: utf-8 -*-
# Generated by protocol buffer compiler.  DO NOT EDIT!!!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'node_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12node_service.proto\x12\x0b\x66\x65\x64med.node\"d\n\x13RegisterNodeRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x15\n\rhospital_name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x61taset_size\x18\x04 \x01(\x05\"R\n\x14RegisterNodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10server_time_unix\x18\x03 \x01(\x03\"=\n\x10HeartbeatRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x18\n\x10\x63lient_time_unix\x18\x02 \x01(\x03\"C\n\x11HeartbeatResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x18\n\x10server_time_unix\x18\x02 \x01(\x03\"\x16\n\x14GetNodeStatusRequest\"\x93\x01\n\x0fNodeStatusEntry\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x15\n\rhospital_name\x18\x02 \x01(\t\x12%\n\x05state\x18\x03 \x01(\x0e\x32\x16.fedmed.node.NodeState\x12\x1b\n\x13last_heartbeat_unix\x18\x04 \x01(\x03\x12\x14\n\x0c\x64\x61taset_size\x18\x05 \x01(\x05\"=\n\x0eNodeStatusList\x12+\n\x05nodes\x18\x01 \x03(\x0b\x32\x1c.fedmed.node.NodeStatusEntry*;\n\tNodeState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0b\n\x07SUSPECT\x10\x02\x12\x08\n\x04\x44\x45\x41\x44\x10\x03\x32\xff\x01\n\x0bNodeService\x12S\n\x0cRegisterNode\x12 .fedmed.node.RegisterNodeRequest\x1a!.fedmed.node.RegisterNodeResponse\x12J\n\tHeartbeat\x12\x1d.fedmed.node.HeartbeatRequest\x1a\x1e.fedmed.node.HeartbeatResponse\x12O\n\rGetNodeStatus\x12!.fedmed.node.GetNodeStatusRequest\x1a\x1b.fedmed.node.NodeStatusListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODESTATE']._serialized_start=590
  _globals['_NODESTATE']._serialized_end=649
  _globals['_REGISTERNODEREQUEST']._serialized_start=35
  _globals['_REGISTERNODEREQUEST']._serialized_end=135
  _globals['_REGISTERNODERESPONSE']._serialized_start=137
  _globals['_REGISTERNODERESPONSE']._serialized_end=219
  _globals['_HEARTBEATREQUEST']._serialized_start=221
  _globals['_HEARTBEATREQUEST']._serialized_end=282
  _globals['_HEARTBEATRESPONSE']._serialized_start=284
  _globals['_HEARTBEATRESPONSE']._serialized_end=351
  _globals['_GETNODESTATUSREQUEST']._serialized_start=353
  _globals['_GETNODESTATUSREQUEST']._serialized_end=375
  _globals['_NODESTATUSENTRY']._serialized_start=378
  _globals['_NODESTATUSENTRY']._serialized_end=525
  _globals['_NODESTATUSLIST']._serialized_start=527
  _globals['_NODESTATUSLIST']._serialized_end=588
  _globals['_NODESERVICE']._serialized_start=652
  _globals['_NODESERVICE']._serialized_end=907
# @@protoc_insertion_point(module_scope)
