# Generated by gRPC Python protocol compiler plugin. DO NOT EDIT!
"""The client and the server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import training_control_pb2 as training__control__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in training_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainingControlServiceStub:
    """TrainingControlService carries round-level control signals between the
    central server and hospital nodes. It does NOT carry model weights —
    that exchange is handled by Flower's own client/server channel.
    This service exists so your distributed-systems layer can tell nodes
    "a round is starting" / "we got your update" independently of the FL
    framework's internals, which keeps orchestration and resilience logic
    decoupled from the ML training loop.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyRoundStart = channel.unary_unary(
                '/fedmed.control.TrainingControlService/NotifyRoundStart',
                request_serializer=training__control__pb2.RoundStartNotice.SerializeToString,
                response_deserializer=training__control__pb2.Ack.FromString,
                _registered_method=True)
        self.SubmitUpdateAck = channel.unary_unary(
                '/fedmed.control.TrainingControlService/SubmitUpdateAck',
                request_serializer=training__control__pb2.UpdateAck.SerializeToString,
                response_deserializer=training__control__pb2.Ack.FromString,
                _registered_method=True)


class TrainingControlServiceServicer:
    """TrainingControlService carries round-level control signals between the
    central server and hospital nodes. It does NOT carry model weights —
    that exchange is handled by Flower's own client/server channel.
    This service exists so your distributed-systems layer can tell nodes
    "a round is starting" / "we got your update" independently of the FL
    framework's internals, which keeps orchestration and resilience logic
    decoupled from the ML training loop.
    """

    def NotifyRoundStart(self, request, context):
        """Server -> Node: announces a new round is starting and the node is selected.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitUpdateAck(self, request, context):
        """Node -> Server: confirms it has submitted its model update to Flower's
        aggregation channel for this round (used for tracking/timeout logic).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyRoundStart': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyRoundStart,
                    request_deserializer=training__control__pb2.RoundStartNotice.FromString,
                    response_serializer=training__control__pb2.Ack.SerializeToString,
            ),
            'SubmitUpdateAck': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitUpdateAck,
                    request_deserializer=training__control__pb2.UpdateAck.FromString,
                    response_serializer=training__control__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fedmed.control.TrainingControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fedmed.control.TrainingControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingControlService:
    """TrainingControlService carries round-level control signals between the
    central server and hospital nodes. It does NOT carry model weights —
    that exchange is handled by Flower's own client/server channel.
    This service exists so your distributed-systems layer can tell nodes
    "a round is starting" / "we got your update" independently of the FL
    framework's internals, which keeps orchestration and resilience logic
    decoupled from the ML training loop.
    """

    @staticmethod
    def NotifyRoundStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedmed.control.TrainingControlService/NotifyRoundStart',
            training__control__pb2.RoundStartNotice.SerializeToString,
            training__control__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitUpdateAck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedmed.control.TrainingControlService/SubmitUpdateAck',
            training__control__pb2.UpdateAck.SerializeToString,
            training__control__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
